### ISSUE TITLE
Upgrade to Geocoder 3.0.0

### ISSUE THREAD

**Issue by willdurand** [geocoder-php/geocoder-extra#19]

**Comment by elazar** [comment]
+1

Related: geocoder-php/geocoder-extra#25

**Comment by collmomo** [comment]
+1

**Comment by romainneutron** [comment]
See also #32

**Comment by vicchi** [comment]
What's the current status of this repo? It seems ... unloved, with a v3 supporting branch that's partially implemented and a `master` branch that doesn't seem to build/test cleanly.

The reason I ask is not to grouch or moan. I'm wanting to add two new providers and in its current state I'm wondering whether it's worth doing the work to get this repo building cleanly for v3 (assuming I have the time) before thinking about starting on the new providers.

Also, and related to the above, what's the relationship between this repo and the main `Geocoder` repo? I can see that there's more (putting it politely) _niche_ geocoders here, but I would have expected the HERE geocoder to be part of the main repo and not this one. Is there a rationale behind this or just the way it's happened?

Apologies for the barrage of questions; I'll go and make more coffee now

**Comment by vicchi** [comment]
With the added offer that I'm more than happy to get this repo working with v3 if @willdurand or anyone else on the project wants to take this offer up.

**Comment by Nyholm** [comment]
I just started to make sure it is working with Geocoder 3.0. I would be happy if you reviewed my PR. Coming up shortly...

**Comment by vicchi** [comment]
@Nyholm Delighted to! I'll watch out for the PR.

**Comment by Nyholm** [comment]
I've added #38 which will fix the build status in master. 

Does it make sense to tag 2.0 for geocoder-extra that supports geocoder:3.0 and then within a few month tag 3.0 for geocder-extra that supports geocoder 4.0?

**Comment by vicchi** [comment]
> I've added #38 which will fix the build status in master.

I've just pulled your `build` branch into my local fork and run the unit tests. I'm getting 5 failures ...

```
) Geocoder\Tests\Provider\GeocoderCaProviderTest::testgeocodeWithRealAddressUS
Failed asserting that '38.898761' matches expected 38.874580000000002.

/Users/gary/Projects/what3words/geocoder/geocoder-extra/tests/Geocoder/Tests/Provider/GeocoderCaProviderTest.php:83

2) Geocoder\Tests\Provider\GeocodioProviderTest::testGetGeocodedDataWithAddressGetsNullContent
Failed asserting that exception message 'Could not find results for given query: http://api.geocod.io/v1/geocode?q=1+Infinite+Loop+Cupertino%2C+CA+95014&api_key=9999' contains 'Could not execute query: http://api.geocod.io/v1/geocode?q=1+Infinite+Loop+Cupertino%2C+CA+95014&api_key=9999'.

3) Geocoder\Tests\Provider\IpGeoBaseProviderTest::testGetGeocodedDataWithRealIPv4Kiev
Failed asserting that 0.0 matches expected 50.450001.

/Users/gary/Projects/what3words/geocoder/geocoder-extra/tests/Geocoder/Tests/Provider/IpGeoBaseProviderTest.php:134

4) Geocoder\Tests\Provider\TelizeProviderTest::testGetGeocodedDataWithRealIPv4GetsNullContent
Failed asserting that exception message 'Invalid result returned by provider.' contains 'Could not execute query http://www.telize.com/geoip/88.188.221.14'.

5) Geocoder\Tests\Provider\TelizeProviderTest::testGetGeocodedDataWithRealIPv4GetsEmptyContent
Failed asserting that exception message 'Invalid result returned by provider.' contains 'Could not execute query http://www.telize.com/geoip/88.188.221.14'.

FAILURES!
Tests: 160, Assertions: 955, Errors: 4, Failures: 5, Skipped: 10.
```

... does that match with your results? If so, this is a massive step forward.

> Does it make sense to tag 2.0 for geocoder-extra that supports geocoder:3.0 and then within a few month tag 3.0 for geocder-extra that supports geocoder 4.0?

Would it not make more sense to align the version tags across these two repos, at least at the major version number?

As an aside and to be honest, I'm still struggling with the concept of what providers _belong_ in this repo and what provider should, to my thinking at least, be _promoted_ to the main `Geocoder` repo.

**Comment by Nyholm** [comment]
Yes, that is my results as well. 

The Telize service seams to be down, same with the Geocodio service. 

> Would it not make more sense to align the version tags across these two repos, at least at the major version number?

It depends how related you what the packages to be. I think the best solution is to let packages be small and independent.


> As an aside and to be honest, I'm still struggling with the concept of what providers belong in this repo and what provider should, to my thinking at least, be promoted to the main Geocoder repo.

I do not have a good answer to that. I let someone else answer that.

**Comment by vicchi** [comment]
> The Telize service seams to be down, same with the Geocodio service.

geocod.io is still up but I think that the API key that the tests are used is invalid as 
`http://api.geocod.io/v1/geocode?q=1+Infinite+Loop+Cupertino%2C+CA+95014&api_key=[redacted]` yields

```
{
error: "Invalid API key"
}
```

The public Telize service is dead. `http://www.telize.com/` has a notice saying "The public API will permanently shut down on November 15th, 2015".

So at the very least we should disable the unit tests for that provider, but probably keep the provider code in situ for any users who are on one of their paid plans (the paid API is still available apparently).

> It depends how related you what the packages to be. I think the best solution is to let packages be small and independent.

A very valid point.

**Comment by vicchi** [comment]
I've done a bit of digging into the other unit test failures ...

```
1) Geocoder\Tests\Provider\GeocoderCaProviderTest::testgeocodeWithRealAddressUS
Failed asserting that '38.898761' matches expected 38.874580000000002.
```

This seems to be down to a changed coordinates being returned by Geocoder.ca. Geocoding "1600 Pennsylvania Ave, Washington, DC" returns the following

```
<geodata>
	<latt>38.898761</latt>
	<longt>-77.035117</longt>
	<AreaCode>202</AreaCode>
	<TimeZone>America/New_York</TimeZone>
	<standard>
		<stnumber>1600</stnumber>
		<staddress>Nw Pennsylvania Ave</staddress>
		<city>Washington</city>
		<prov>DC</prov>
		<postal>20502</postal>
		<confidence>0.9</confidence>
	</standard>
</geodata>
```

The coordinates being tested don't match the return value; updating the test with the (current) coordinates fixes this.

```
2) Geocoder\Tests\Provider\GeocodioProviderTest::testGetGeocodedDataWithAddressGetsNullContent
Failed asserting that exception message 'Could not find results for given query: http://api.geocod.io/v1/geocode?q=1+Infinite+Loop+Cupertino%2C+CA+95014&api_key=9999' contains 'Could not execute query: http://api.geocod.io/v1/geocode?q=1+Infinite+Loop+Cupertino%2C+CA+95014&api_key=9999'.
```

This has me stumped. I'm trying - and currently failing - to work out why this call is failing.

```
3) Geocoder\Tests\Provider\IpGeoBaseProviderTest::testGetGeocodedDataWithRealIPv4Kiev
Failed asserting that 0.0 matches expected 50.450001.
```

The IP address being tested doesn't seem to exist anymore; checking other IP to Geo lookup services seems to corroborate this as well as a call to `http://ipgeobase.ru:7020/geo?ip=2.56.176.1` now returns

```
<ip-answer>
	<ip value="2.56.176.1">
		<message>Not found</message>
		</ip>
</ip-answer>
```

As a result I've flagged this test as skipped for now with a message that we need a real IP address to test against.

Overall, we're down to a single test failure now for Geocod.io. Which is progress

**Comment by willdurand** [comment]
Great work here! If a provider is not working anymore, let's drop it!

**Comment by vicchi** [comment]
Thanks @willdurand ... while I have your attention ...

I asked ...

> As an aside and to be honest, I'm still struggling with the concept of what providers belong in this repo and what provider should, to my thinking at least, be promoted to the main Geocoder repo.

And @Nyholm said ...

> I do not have a good answer to that. I let someone else answer that.

Any comments to add?

**Comment by willdurand** [comment]
(I am replying to all of your points)

**Comment by vicchi** [comment]
Premature posting on my part! Apologies.

Also if someone can merge in @Nyholm's PR I can then fix up the unit tests with my changes, which are based on the contents of PR #38

**Comment by willdurand** [comment]
Hi!

> What's the current status of this repo? It seems ... unloved, with a v3 supporting branch that's partially implemented and a master branch that doesn't seem to build/test cleanly.

It is partially maintained.. To be honest, I failed at fixing all these providers alone...

> The reason I ask is not to grouch or moan. I'm wanting to add two new providers and in its current state I'm wondering whether it's worth doing the work to get this repo building cleanly for v3 (assuming I have the time) before thinking about starting on the new providers.

This repo MUST be stable again, because it contains a lot of providers.

> Also, and related to the above, what's the relationship between this repo and the main Geocoder repo?

Geocoder extra contains providers for Geocoder that are rather specific: most of them are country-specific for instance. They don't belong to the Geocoder "core" because you should be able to switch from one provider to another without having to think. It works well with "core" providers because they can geocode addresses worldwide. That is not the case of the providers in the Geocoder extra package.

Anyway, both are "official" even if I must admit that Geocoder extra did not get enough attention over the last year...

> I can see that there's more (putting it politely) niche geocoders here, but I would have expected the HERE geocoder to be part of the main repo and not this one. Is there a rationale behind this or just the way it's happened?

Nope, or maybe it is because that one provides too few information, still related to the desire of switching from one provider to another without loosing anything.
 
> Apologies for the barrage of questions; I'll go and make more coffee now

No problem. Feel free to ask anything! If you want to give a hand, I'd be happy too!

> With the added offer that I'm more than happy to get this repo working with v3 if @willdurand or anyone else on the project wants to take this offer up.

Sure. I can make you a maintainer of this project!

> Would it not make more sense to align the version tags across these two repos, at least at the major version number?

I don't think so, but if you think it is better/easier, then we can totally align version numbers, at least the major numbers.

> As an aside and to be honest, I'm still struggling with the concept of what providers belong in this repo and what provider should, to my thinking at least, be promoted to the main Geocoder repo.

When I designed Geocoder, my goal was to have a uniform geocoding layer across multiple providers. When I started Geocoder extra, I moved all providers that did not fit this requirement. In this package (extra), everyone can contribute providers that are country specific, or that provide less information than the others.

**Comment by vicchi** [comment]
> Sure. I can make you a maintainer of this project!

Would be delighted to. Both these projects have proved invaluable to me over the last couple of years so I'd be really happy to contribute something back. Thanks for the offer, consider it accepted.

> When I designed Geocoder, my goal was to have a uniform geocoding layer across multiple providers. When I started Geocoder extra, I moved all providers that did not fit this requirement. In this package (extra), everyone can contribute providers that are country specific, or that provide less information than the others.

That makes perfect sense. I do think that some rationalisation would be useful here as the HERE geocoder (disclaimer, I used to work for Ovi/Nokia/HERE maps) really belongs in the `Geocoder` repo, at least to my way of thinking.

> I don't think so, but if you think it is better/easier, then we can totally align version numbers, at least the major numbers.

Let's revisit this and discuss once we're closer to getting both repos stable and ready to release a new version.

> This repo MUST be stable again, because it contains a lot of providers.

I have a long flight ahead of me this weekend, plus time mooching at the back of a conference. I now have something worthwhile to occupy my time!

**Comment by willdurand** [comment]
> Would be delighted to. Both these projects have proved invaluable to me over the last couple of years so I'd be really happy to contribute something back. Thanks for the offer, consider it accepted.

Then, welcome on board! (cc @geocoder-php/geocoder)



> That makes perfect sense. I do think that some rationalisation would be useful here as the HERE geocoder (disclaimer, I used to work for Ovi/Nokia/HERE maps) really belongs in the Geocoder repo, at least to my way of thinking.

I am not against this, but we have to move it before the upcoming major release that @Nyholm is leading :)

> I have a long flight ahead of me this weekend, plus time mooching at the back of a conference. I now have something worthwhile to occupy my time!


Thank you <3

**Comment by Nyholm** [comment]
Im going to close this issue. @vicchi has done a great job making sure this library is ready for the next release.

**Comment by vicchi** [comment]
@Nyholm Thank you (takes a small virtual bow). We've come a long way since I first posted on this issue on 8/9! It's fabulous to see this all making progress and moving forwards. Great to be part of it.
