### ISSUE TITLE
Provider interface missing ? 

### ISSUE THREAD

**Issue by collmomo** [geocoder-php/geocoder-extra#23]
```php[Symfony\Component\Debug\Exception\ClassNotFoundException]                           
  Attempted to load interface "ProviderInterface" from namespace "Geocoder\Provider".  
  Did you forget a "use" statement for another namespace?    

 Exception trace:
() at /Library/WebServer/Documents/immobilier/vendor/geocoder-php/geocoder-extra/src/Geocoder/Provider/HereProvider.php:22```

//After copying from internet
                                                                                                                    
  ```php[Symfony\Component\Debug\Exception\FatalErrorException]                                                            
  Error: Class Geocoder\Provider\HereProvider contains 1 abstract method and must therefore be declared abstract or  
   implement the remaining methods (Geocoder\Provider\ProviderInterface::setMaxResults)                              
                                                                                                                     
Exception trace:
 () at /Library/WebServer/Documents/immobilier/vendor/geocoder-php/geocoder-extra/src/Geocoder/Provider/HereProvider.php:177```

**Comment by toin0u** [comment]
@collmomo Thanks for reporting this issue. Which version do you use? Can you maybe provide your composer.json :)

**Comment by collmomo** [comment]
"php": ">=5.3.3",
        "symfony/symfony": "2.6.*",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "~1.2",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0",
        "sensio/framework-extra-bundle": "~3.0",
        "incenteev/composer-parameter-handler": "~2.0",
        "jasonlewis/expressive-date": "1.0.*",
        "sunra/php-simple-html-dom-parser": "v1.5.0",
        "fabpot/goutte": "2.0.*@dev",
        "neitanod/forceutf8": "dev-master",
        "bcc/cron-manager-bundle": "v2.6",
        "willdurand/geocoder": "3.0.*@dev",
        "malenki/math": "dev-master",
        "twbs/bootstrap": "3.3.*@dev",
        "mexitek/phpcolors": "dev-master",
        "hannesvdvreken/pip": "dev-master",
        "jms/serializer-bundle": "0.13.*@dev",
        "phayes/geophp": "dev-master",
        "nesbot/carbon": "dev-master",
        "intervention/image": "dev-master",
        "geocoder-php/geocoder-extra": "2.0.*@dev"

**Comment by willdurand** [comment]
Well, `dev` should not be used. This lib is not ready for Geocoder v3.0.

**Comment by toin0u** [comment]
@collmomo As Will said you need to use the `~1.4` version https://packagist.org/packages/geocoder-php/geocoder-extra#v1.4.0 which will Geocoder `~2.0` (which means >=2.0 but <3.0).

**Comment by collmomo** [comment]
@willdurand @toin0u Thanks for your help guys, those type of packages make php feel much more like a real and complete language. You make it possible to get away from the free for all php. Cheers !!

**Comment by toin0u** [comment]
@collmomo thanks a lot for your kind words! Do not hesitate to ask if you need any help :)
