### ISSUE TITLE
Feature request: method to check point in polygon

### ISSUE THREAD

**Issue by RomeroMsk** [geocoder-php/geocoder-extra#26]
Add method to check if point is inside polygon. It can be useful, for example, to check if delivery address is inside delivery zone.
The algorithm is simple.

**Comment by willdurand** [comment]
I think it is out of scope of the lib. Did you consider https://github.com/thephpleague/geotools?

**Comment by RomeroMsk** [comment]
I created this issue because of
> This repository hosts Geocoder extra features that do not belong to the core but can be nonetheless interesting to share with other developers.
I thought it can be useful extra feature for Geocoder.

**Comment by willdurand** [comment]
Geotools already contains a lot of features for Geocoder.

**Comment by RomeroMsk** [comment]
Ok, I understand.
