### ISSUE TITLE
Geocodio fixes not in stable package

### ISSUE THREAD

**Issue by patrickcarlohickman** [geocoder-php/geocoder-extra#28]
PR #21 fixed some issues with the Geocodio provider, but it looks like it was only merged into the 1.x branch. Is it possible to get this merged into a tagged release?

Let me know if there are any questions, or if my understanding is incorrect. Thanks!

**Comment by vicchi** [comment]
@willdurand Looks like this is still the case as the `1.x` branch is 4 commits ahead of `master`?

**Comment by willdurand** [comment]
ahm maybe yes. so we should:

1. tag a version for `1.x`
2. and then merge `1.x` into `master` (which might be a little bit tricky)

**Comment by vicchi** [comment]
@willdurand Tagging `1.x` retrospectively is a good idea. Maybe a cherry pick merge for point 2 might work though I'd assume this depends on how much drift there's been since `1.x` was last updated.

**Comment by Nyholm** [comment]
Lets cherry pick the commit and put it to master.

**Comment by Nyholm** [comment]
Fixed in #46
