### ISSUE TITLE
Add Mapzen Search as a provider

### ISSUE THREAD

**Issue by stevevance** [geocoder-php/geocoder-extra#29]
[Mapzen Search](https://mapzen.com/documentation/search/) (also known as Pelias) is free and open source. 

How do I make a new provider?

**Comment by vicchi** [comment]
@stevevance I've got a working implementation of a provider for Mapzen in test. Should be added as a supported provider sometime towards the latter end of next week.

**Comment by stevevance** [comment]
@vicchi That's fantastic. Let me know if you want me to test it.

**Comment by vicchi** [comment]
@stevevance See https://github.com/geocoder-php/Geocoder/pull/531 for the first working pass at supporting Mapzen's geocoder.

**Comment by vicchi** [comment]
Mapzen is now implemented as a supported provider in the main Geocoder project, so I'm closing this issue.

**Comment by willdurand** [comment]
:+1:
