### ISSUE TITLE
Provider for Dutch address look-up based on postal code and housenumber

### ISSUE THREAD

**Issue by jessevanmuijden** [geocoder-php/geocoder-extra#30]
I am planning to work on a provider for Dutch address look-up based on postal code and housenumber with this API: https://api.postcode.nl/documentation. Is this the right place to add it? If so, I can make a PR today.

**Comment by vicchi** [comment]
@jessevanmuijden This is absolutely the right place; looking forwards to seeing your PR.

**Comment by vicchi** [comment]
@jessevanmuijden - any progress on making a PR available?

**Comment by jessevanmuijden** [comment]
no, sorry, my company reduced the priority of this feature, so i did not
get time to work on it.

**Comment by vicchi** [comment]
Don't worry. These things happen. I'll close this issue but if you get the opportunity, we'd love to have this added as a provider in the future.
